### PR TITLE
hasPreservationMaster

### PR DESCRIPTION
**Pull request by dannylamb**
** Github issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/588

# What does this Pull Request do?

Adds an ontology with a single property, hasPreservationMaster, which is a refinement of pcdm:hasFile and will be used by our 'OBJ' field in CLAW.

# What's new?
Some rdfxml

# How should this be tested?

People who know more about this stuff should look at it and tell me if i'm out to lunch.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by manez** [comment]
Beating @ruebot to the punch...

image

**Comment by whikloj** [comment]
😢  no merge access for jared

**Comment by acoburn** [comment]
Can I recommend a different path for this?

First, don't use RDF/XML -- it's terrible.

Use Turtle, that way you can read it. 

Then automate the creation of different serializations. Take a look here for an example: https://github.com/trellis-ldp/trellis-ontology

it is really, really easy to push it to a server and have the server do conneg on those different serializations; you can see an example here: https://acdc.amherst.edu/ns/trellis

**Comment by acoburn** [comment]
My other point on this, and @ajs6f will probably agree, but don't use this to refine PCDM. Simply let this be its own thing. If you want to use `claw:hasPreservationMaster`, just use that. If you are planning to use it as a refinement of `pcdm:hasFile`, wouldn't you need to include the `pcdm:hasFile` triple anyway (at least if you want to support clients that can't infer triples)? So then what's the value of basing this on PCDM? If I were you, I'd make this ontology use the following existing vocabularies and no others: `owl`, `rdf`, `rdfs`, `dcterms`.

**Comment by acoburn** [comment]
And another comment: what value does this property have over the existing `pcdmuse:PreservationMasterFile`? That is, what is the difference, semantically between:

    <> claw:hasPreservationMaster </otherResource>

and 

    <> pcdm:hasFile </otherResource> .
    </otherResource> a pcdmuse:PreservationMasterFile .

**Comment by acoburn** [comment]
Here is another example of an ontology project https://gitlab.amherst.edu/acdc/acrepo-ontology

And the published ontology: https://acdc.amherst.edu/ns/amherst

**Comment by ajs6f** [comment]
I'm pretty much +1 to what @acoburn says.

You don't benefit from inheriting from PCDM. Inheriting from an upper ontology is worthwhile to the extent that the upper ontology doesn't cover the same ground as yours. PCDM doesn't really have a well-defined domain (it doesn't talk about anything real-as-in-outside-the-repo-ecosystem-itself, it just reifies filesystem-like notions into the repo) so that doesn't apply at all; it's just not ever going to be a good idea to inherit from PCDM.

Rinke Hoekstra made his Ph.D thesis into [a really good book](http://www.worldcat.org/title/ontology-representation-design-patterns-and-ontologies-that-make-sense/oclc/326418405) that can help you work through this kind of thing. Much recommended.

**Comment by dannylamb** [comment]
## Full Disclosure
I'd rather not have an ontology at all.  So if it's possible to not have one, then I'm all for it.  The less opportunities for folks to derail CLAW, the better.  If implying a relationship is sufficient without explicitly stating it with a relationship, then I'm game.

**Comment by ajs6f** [comment]
Generally, multiplying types is going to be stronger in the long term than multiplying properties.

**Pull request closed without merging**
